### ISSUE TITLE
2.3 Combine 2 SOQL into 1 (get related records from Flight)

### ISSUE THREAD

**Issue by NikitaErmakSenla** [sanek00789/sf-senla-courses#20]
https://github.com/sanek00789/sf-senla-courses/blob/401042a074fb6a6aeba1c173c79881283717866d/lecture_2.3/FlightTriggerWithHandler.cls#L10

**Comment by sanek00789** [comment]
Не объединял в один запрос, потому что посчитал, что так не будет работать. Например ситуация когда в базе нет ни одного рейса и добавляется первый рейс,  тогда запрос не сработает и валидация не произойдет. Или ситуация, когда уже есть рейсы и добавляется новый рейс, в котором добавлены турист и поездка, которые до этого не добавлялись не в один из рейсов, тогда мы не сможем взять из запроса из существующих рейсов информацию о возрасте туриста и дате поездки, поэтому валидация, наверно, тоже не сработает.
Возможно я ошибаюсь) но пока считаю так)
