### ISSUE TITLE
2.3 naming: newTourists -> touristMap (it's a Map there, not a List)

### ISSUE THREAD

**Issue by NikitaErmakSenla** [sanek00789/sf-senla-courses#25]
https://github.com/sanek00789/sf-senla-courses/blob/401042a074fb6a6aeba1c173c79881283717866d/lecture_2.3/TouristTriggerHandler.cls#L4

**Comment by sanek00789** [comment]
done

**Comment by NikitaErmakSenla** [comment]
By the way, _newMap_ is better. 
Often we pass oldMap & newMap to such kind of methods
