### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by ekevra** [sanek00789/sf-senla-courses#52]
https://github.com/sanek00789/sf-senla-courses/blob/28da8447de1866fd9b0d88c9b1d3aef6d4297b92/lecture_2.5/TouristCustomDataManager.cls#L1

CustomMetadataTypeManager will be better (or just EmailCustomMetadataManager, EmailCustomMetadataTypeManager)

**Comment by NikitaErmakSenla** [comment]
Verified (can be closed)
