### ISSUE TITLE
Name of field is bad

### ISSUE THREAD

**Issue by ekevra** [sanek00789/sf-senla-courses#53]
https://github.com/sanek00789/sf-senla-courses/blob/28da8447de1866fd9b0d88c9b1d3aef6d4297b92/lecture_2.5/TouristCustomDataManager.cls#L1
 
Custom Metadata Type назван Email, это значит, что сюда вы сможете добавлять все имейлы, необходимые вашей организации. Поэтому поле. которое будет хранить электронный адрес так и должно называться: Email address

**Comment by NikitaErmakSenla** [comment]
Verified (can be closed)

FYI Email_Address would be better
