### ISSUE TITLE
2.6.4 why is not used getByNamesAndEmails?

### ISSUE THREAD

**Issue by alexCherrySfds2019** [sanek00789/sf-senla-courses#62]
https://github.com/sanek00789/sf-senla-courses/blob/61c69f30ab408ea9d2c4386412837ce2da0187f7/lecture_2.6/TouristRestService.cls#L46

**Comment by sanek00789** [comment]
не использовал этот метод потому, что в задании надо было создать метод, который создает одного туриста, а у метода getByNamesAndEmails во входящих параметрах сет имен и сет мейлов, поэтому посчитал, что рациональней сделать новый метод getByNameAndEmail с одним именем и мэйлом

**Comment by NikitaErmakSenla** [comment]
Verified (can be closed)
